name: Health
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^4.0.0
  http: ^0.12.0+4
  uuid: ^2.0.4
  barcode_scan: ^2.0.1

  qr_flutter: ^3.2.0
  flutter_svg: ^0.18.1
  speech_to_text: ^2.3.0
  highlight_text: ^0.7.2
  avatar_glow: ^1.2.0
  scoped_model: ^1.0.1
  moor_flutter: ^2.0.0
  google_maps_flutter: ^0.5.11
  geolocator: ^6.1.13
  image_picker:
  simple_animations: ^1.3.4
  flutter_local_notifications: ^0.8.4+3
  animated_splash_screen: ^1.0.1+2
  fluttertoast: ^7.1.1
  dio: ^3.0.3
  bubble: ^1.1.9+1
  sqflite: ^1.3.1+1
  path: ^1.7.0
  timezone: ^0.5.9
  animated_text_kit: ^2.5.3
  animated_widgets: ^1.0.6
  flutter_dialogflow: ^0.1.3
  auto_size_text: ^2.1.0
  firebase_core: ^0.5.0+1
  font_awesome_flutter: ^8.4.0
  firebase_messaging: ^7.0.3
  decimal: ^0.3.3
  pedometer: ^0.0.5
  percent_indicator: ^1.0.14
  firebase_auth: ^0.18.1+2
  firebase_database: ^4.1.1
  flutter_facebook_login: ^3.0.0
  firebase_storage:
  shared_preferences:
  grouped_list: ^3.7.1
  google_sign_in: ^4.5.9
  flutter_localizations:
    sdk: flutter


    # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^3.2.3

    # Package provides internalization and localization facilities, including message translation,
    # plurals and genders, date/number formatting and parsing, and bidirectional text.
  intl: ^0.16.0

    # Flutter library to load and cache network images. Can also be used with placeholder and
    # error widgets.
  cached_network_image: ^2.0.0-rc
  flutter_stetho: ^0.5.0
    # Tools to write binaries that run builders.
  build_runner: ^1.7.1



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  url_launcher: ^5.5.3
  sign_button: ^1.0.1
  provider:


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/logo1.png
     - assets/logo3.png
     - assets/cal.png
     - assets/map.png
     - assets/QR.png
     - assets/chat.png
     - assets/pill.png
     - assets/know.png
     - assets/first.png
     - assets/News.png
     - assets/momo.png
     - assets/kill.png
     - assets/food.png
     - assets/logo12.png
     - assets/caugh.png
     - assets/fever.png
     - assets/headache.png
     - assets/map1.png
     - assets/virus.png
     - assets/wash_hands.png
     - assets/wear_mask.png
     - assets/drug.png
     - assets/emergency.png
     - assets/inhaler.png
     - assets/man_avatar.png
     - assets/ointment.png
     - assets/pill_rounded.png
     - assets/pill1.png
     - assets/syringe.png
     - assets/aid1.png
     - assets/Note.png
     - assets/profile.png
     - assets/clock.png
     - assets/map2.png
     - assets/healthy-food.png
     - assets/eat.png


     - assets/icons/
     - assets/images/
     - assets/service.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
